require('User')

local user = User.new()
user.login('11111')
print(user.getUsername())
user.logOut()
print(user.getUsername())
user.login('22222')
print(user.getUsername())
user.login('33333')
print(user.getUsername())
user.login('44444')
print(user.getUsername())
user.login('55555')
print(user.getUsername())
user.login('66666')
print(user.getUsername())
user.login('77777')
print(user.getUsername())
user.login('88888')
print(user.getUsername())
