cc_test(
  name = "libgui_test",
  srcs = ["libgui_test.cc"],
  deps = [
   "//libgui:libgui",
   "//liblua:liblua",
   "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "libdb_test",
  srcs = ["libdb_test.cc"],
  deps = [
   "//libdb:libdb",
   "//liblua:liblua",
   "@googletest//:gtest_main"
  ]
)